name: Build App

on:
  create:
    tags:
      - v*

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  DOCKER_IMAGE_NAME: umms-gb
  REGISTRY_HOSTNAME: gcr.io

jobs:
  setup-build-app:
    name: build and push app
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
      
    # Build the Docker image
    - name: Build
      run: |        
        docker build -t "$REGISTRY_HOSTNAME"/"$GKE_PROJECT"/"$DOCKER_IMAGE_NAME":"${GITHUB_REF/refs\/tags\//}" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" .  
    
    - name: Push Docker Image
      run: |
          docker push "$REGISTRY_HOSTNAME"/"$GKE_PROJECT"/"$DOCKER_IMAGE_NAME":"${GITHUB_REF/refs\/tags\//}"
    
  